title: Stephanie Cannon
description: Portfolio
email: steph@sparkthecannon.com
url: https://sparkthecannon.com
github_username: pauheading

# Server config
livereload : true

# Build settings
markdown : kramdown
theme    : futuro

exclude :

  - node_modules
  - gulp
  - gulpfile.js

setup :

  install : theme
  display : block
  respond : true
  share   : false

defaults      :

- scope       :
    path      : ''
  values      :
    layout    : single
    type      : empty
