title: Stephanie Cannon
description: Portfolio
email: hello@stephaniecannon.co.uk
url: https://stephaniecannon.co.uk
github_username: pauheading

# Server config
livereload : true
include    : [_redirects]
host       : 0.0.0.0

# Build settings
markdown : kramdown
theme    : futuro

defaults    :
- scope     :
    path    : ""
  values    :
    layout  : default
